// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnftifxlsepcawvrprnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZnRpZnhsc2VwY2F3dnJwcm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDE4NDEsImV4cCI6MjA2MTg3Nzg0MX0.UikS4Yca7BtpsTRCtxlpZM1UCP1VthAWa4D4epI3ka4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);